### PR TITLE
Clean up/Fix dependencies/Fix deprecation/New tools etc.

### PR DESCRIPTION
**Pull request by ThomasHowarth**
This PR does lots of things:

1. Added PelePhysics as a Submodule - this allows for "out-of-the-box" compilation. We should probably set up some CI so that all the dependency and deprecation issues get caught and we don't have to do this again. Perhaps @baperry2 can offer some suggestions for this?
2. Fixed many deprecated function calls (too many to individually list here). There is one tool that I can't figure out what the appropriate fix is (avgToPlane). Additionally, I will be putting some work in to get partStream to full functionality, and then the old streamlines tools can be removed, which should remove any legacy fortran code.
3. Lots of tidying, including removing old files. This includes: 
            - Collecting all python scripts and input samples together and removing Matlab scripts - this also tidied up the top directory structure 
            - Deleted tools: BuildPMF (this is now integrated into PelePhysics), Process and blowOut (these were sort of templates, but I've now just made a template one instead), bruno (out of ModelSpecific), avgPlotfiles (I replaced this with avgPlotfilesFlexible, which just seems like a strict upgrade).
4. Fixed dependencies for ModelSpecificAnalysis - this should just work out of the box.
5. Some new tools:
            - decimateMEF: This works using qslim, which was a popular tool for users a while ago when dealing with large surfaces (@drummerdoc ?). I've integrated it in such a way that qslim itself (now held as a tool) can be built using "make qslim" (and also removed with "make qslimclean") followed by standard compilation of the tool itself
            - integral: One of my own tools that integrates in 1/2/3D and gives dats and ppms
            - combinePlts: An upgrade to combinePlts which allows for reading of multiple files     
6. Simplified the GNUMakefile - there are now two detailed Make.X files in Tools/GNUMake. One for standard analysis, one for modelspecific

If I've been overly-aggressive with file removals/directory structure etc., let me know and I can replace files. In addition to partStream, I also plan on gradually converting old AmrDerive tools (e.g. Spectra), and tidying up my other tools and adding them in.

### CODE REVIEW

**Comment by drummerdoc** [comment]
Thanks for the upgrade to all this.  It's been a long time coming and I appreciate the efforts.  There must be something better than qslim but it has always worked for what I needed...thanks for cleaning that up.  Gonna be a bit tough to do a full detailed review of all this PR though... thanks also for considering the other old analysis tools.  It's going to be great to have many of those in one place.

**Comment by baperry2** [comment]
@ThomasHowarth thanks for all the work on this. As Marc says, there's a lot here, but I have some initial overall comments:

- Adding PelePhysics as a submodule here is something I had wanted to do but never had a chance. I'd also like to have some CI testing as even something very basic could go a long way to keeping the code up to date, but haven't had a chance to do that either. That could be based on what we have in [PelePhyscis](https://github.com/AMReX-Combustion/PelePhysics/blob/development/.github/workflows/ci.yml). We could also include [dependabot](https://github.com/AMReX-Combustion/PelePhysics/blob/development/.github/workflows/ci.yml) submodule updates, but that wouldn't really be helpful until testing is in place. In any event, having PelePhysics as a submodule is a good first step toward having some testing.

- What is the deprecated function call that causes issues for `avgToPlane`?

- I think the reason I left `avgPltFiles` when adding `avgPltFilesFlexible` is that the former may be more efficient when averaging files that have matching boxarrays. But I'm fine to get rid of it as I don't think that's a big deal.

- Can we remove the qslim code and instead either add it as a submodule or download it live during `make qslim` similar to what we do for MAGMA during `make TPL` (https://github.com/AMReX-Combustion/PelePhysics/blob/fe882f0833aa31136b2054ebc30a63cb20528b20/ThirdParty/GNUmakefile#L256)?

- The PeleAnalysis documentation isn't too detailed, but a few changes may be necessary (remove references to deleted tools, add brief entries even if just placeholders for new tools)

**Comment by ThomasHowarth** [comment]
I'll have a play with the CI and documentation, see what I can do. 

For `avgToPlane`, there is a `AMREX_LAUNCH_HOST_DEVICE_FUSIBLE_LAMBDA` function, which specifically takes a `thread_box` which it can't find.

For qslim, the version that we use is a tweaked version of the [original](https://mgarland.org/software/qslim.html), so I can either download from there and overwrite the necessary files with the updated versions that we keep hold of in the repo, or I can host our version on my Github and Submodule/download from there as necessary. Happy to do it either way, but neither is especially clean.

**Comment by drummerdoc** [comment]
I worry that qslim will someday quietly become not available.

**Comment by baperry2** [comment]
I'm not a fan of having a whole copy of a large package that's only needed for one tool directly in the repo. For both compartmentalization and attribution purposes, I'd prefer keep it separate. Given the potential of qslim disappearing and the modifications needed, maybe the best thing would be for us to create a separate qslim repo that we use as a submodule. @drummerdoc - it looks like qslim 2.1 has a GNU license, so it should be fine for us to create a copy as a repo within the AMReX-Combustion organization, right?

**Comment by drummerdoc** [comment]
Sure, that seems fine

**Comment by ThomasHowarth** [comment]
@baperry2 would you like me to remove qslim now, or would you like to take a copy first?

**Comment by baperry2** [comment]
I've created a separate qslim repo that contains the qslim code in this PR, so you can delete the code and submodule that instead: https://github.com/AMReX-Combustion/qslim

@ThomasHowarth if any modifications are needed in the qslim repo, feel free to make them directly

**Comment by ThomasHowarth** [comment]
I've chopped out qslim and integrated it a submodule, many fewer lines of code to review now. Also, should data be loaded using AmrData, which seems to be the case for most tools, and what I'm used to, or PlotFileUtil? I can fix this up for each case also if this is the new standard.

**Comment by drummerdoc** [comment]
Re: AmrData vs PlotFileUtil. I am a fan of AmrData primarily because of its demand-driven I/O.  However, it might be that it will someday become deprecated as we might be the only two or three that use it....unless these tools become popular.  I say we keep it as is.  If we need to migrate to the inferior PlotFileUtil stuff, we can do that later.  My $.02

**Review by baperry2 — APPROVED** [review]
This all looks good to me now. It's much cleaner overall and the remaining things like avgToPlane can be cleaned up in due coarse as needed.

**Comment by drummerdoc** [comment]
Thanks Thomas for all the work here!

**Pull request merged**
